#!/bin/sh
PKGARCH=arm-none-eabi \
PORTLIBSNAME=armv6k \
PKGCONFIGNAME=arm-none-eabi-pkg-config \
CFLAGS="-march=armv6k -mtune=mpcore -mfloat-abi=hard -mtp=soft -O3 -mword-relocations -ffunction-sections" \
LDFLAGS="-march=armv6k -mtune=mpcore -mfloat-abi=hard -mtp=soft" \
pkg-build-base "$@"
