#!/bin/sh
PKGARCH=powerpc-eabi \
PORTLIBSNAME=wii \
PKGCONFIGNAME=wii-pkg-config \
CFLAGS="-DGEKKO -mrvl -mcpu=750 -meabi -mhard-float" \
LDFLAGS="-DGEKKO -mrvl -mcpu=750 -meabi -mhard-float" \
pkg-build-base "$@"
